addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.3.0")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"          % "0.5.0")
addSbtPlugin("net.virtual-void"          % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("org.wartremover"           % "sbt-wartremover"      % "2.4.5")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.10")
